
import collections
import pickle
import opengl.cubes as cubes
import opengl.chunker as chunker
import game_global as gg
import struct
import huffman
import scene_draw
import opengl.image_manip as image_manip
from huffman_generator import generate_huffman_decoder, generate_huffman_encoder

assert gg.M == cubes.m
assert gg.N == cubes.n

save_imgs = False # to save images generated for training as bmp

cubes.cubes_init()

# 'display_args.pkl' is generated by running client.py
# with opengl rendering and environment variable
# LOG_RENDER_ARGS=1
try:
    with open('display_args.pkl', 'rb') as f:
        v = pickle.load(f)
except IOError:
    print("cannot read 'display_args.pkl'.")
    print("maybe try to regenerate it, by running one client like")
    print("$ LOG_RENDER_ARGS=display_args.pkl python3 client.py localhost player")
    raise

print('collecting images')
sequences = []
sequences_int = []
for i, draw_scene_args in enumerate(v):
    pixels = scene_draw.draw_scene(*draw_scene_args)
    chunks = bytearray(len(pixels))
    n_ints = chunker.make_chunks(pixels, chunks, 32)
    sequences.extend(
        ((b, g, r, a), c) for b, g, r, a, c in
         struct.iter_unpack('=BBBBI', chunks[:4*n_ints]))
    sequences_int.extend(struct.iter_unpack('=II', chunks[:4*n_ints]))
    if save_imgs:
        image_manip.export_bmp_py(pixels, "img_gen_huffman_{:03d}.bmp".format(i).encode('ascii'))

# colors
print('generating color encoder/decoder')
colors = [c for c, _ in sequences_int]
_, (codes, tree) = huffman.encode(colors)
print('max color code length:', max(l for s, (s_c, i_c, l) in codes))
generate_huffman_encoder(codes, 'opengl/huffman_encode_colors.cpp')
generate_huffman_decoder(tree, 'opengl/huffman_decode_colors.cpp')
generate_huffman_decoder(tree, '../src/huffman_decode_colors.sv', lang='sv')
avg_color = huffman.huffman_avg_len(colors)

# lengths
print('generating length encoder/decoder')
lengths = [l for _, l in sequences_int]
_, (codes, tree) = huffman.encode(lengths)
print('max length code length:', max(l for s, (s_c, i_c, l) in codes))
generate_huffman_encoder(codes, 'opengl/huffman_encode_lengths.cpp')
generate_huffman_decoder(tree, 'opengl/huffman_decode_lengths.cpp')
generate_huffman_decoder(tree, '../src/huffman_decode_lengths.sv', lang='sv')
avg_length = huffman.huffman_avg_len(lengths)
print('=== Training set performance ===')
chunks_per_frame = len(sequences_int)/len(v)
print('Average chunks per frame: {}'.format(int(chunks_per_frame)))
print('Average pixels per chunk: {:.3g}'.format(800*480/chunks_per_frame))
print('Color average bits: {:.3g}'.format(avg_color))
print('Chunk size average bits: {:.3g}'.format(avg_length))
print('Average bits per chunk: {:.3g}'.format(avg_color + avg_length))
print('Average kbits per frame: {:.3g}'.format((avg_color + avg_length)*chunks_per_frame/1000))

