
WARNING_STR = '// DO NOT EDIT - file generated by game/gen_huffman.py\n'
CASE_STR = 'case 0x{:x}: code = 0x{:03x}; n_bits = {:2}; break;'

def generate_huffman_encoder(codes, filename):
    case_strs = []
    for sym, (code_str, code_int, n_bits) in codes:
        case_strs.append(CASE_STR.format(sym, code_int, n_bits))
    inc_color = '\n'.join(case_strs)
    with open(filename, 'w') as f:
        f.write(WARNING_STR + inc_color + '\n')

# genenrate decoding C code colors
def gen_decode_tree(tree, r_level):
    indent = r_level*' '
    if len(tree) == 2:
        t0, t1 = tree
        return (indent+'if ((code >> {}) & 0x1) {{\n'.format(r_level) +
                gen_decode_tree(t1, r_level+1) +
                '\n'+indent+'} else {\n' +
                gen_decode_tree(t0, r_level+1) +
                '\n'+indent+'}')
    elif len(tree) == 1:
        res, = tree
        return (indent+'decoded = 0x{:x};\n'+indent+'code_len = {};').format(
            res, r_level)
    else:
        raise ValueError(tree)

def generate_huffman_decoder(tree, filename):
    with open(filename, 'w') as f:
        f.write(WARNING_STR + gen_decode_tree(tree, 0) + '\n')
