// DO NOT EDIT - file generated by game/gen_huffman.py
if ((code >> 0) & 0x1) {
 decoded = 0x20;
 code_len = 1;
} else {
 if ((code >> 1) & 0x1) {
  if ((code >> 2) & 0x1) {
   if ((code >> 3) & 0x1) {
    if ((code >> 4) & 0x1) {
     if ((code >> 5) & 0x1) {
      if ((code >> 6) & 0x1) {
       decoded = 0x7;
       code_len = 7;
      } else {
       decoded = 0x1c;
       code_len = 7;
      }
     } else {
      if ((code >> 6) & 0x1) {
       decoded = 0xf;
       code_len = 7;
      } else {
       decoded = 0x1a;
       code_len = 7;
      }
     }
    } else {
     if ((code >> 5) & 0x1) {
      decoded = 0x10;
      code_len = 6;
     } else {
      decoded = 0x5;
      code_len = 6;
     }
    }
   } else {
    if ((code >> 4) & 0x1) {
     if ((code >> 5) & 0x1) {
      decoded = 0x1;
      code_len = 6;
     } else {
      decoded = 0xe;
      code_len = 6;
     }
    } else {
     if ((code >> 5) & 0x1) {
      if ((code >> 6) & 0x1) {
       if ((code >> 7) & 0x1) {
        decoded = 0x19;
        code_len = 8;
       } else {
        decoded = 0x1f;
        code_len = 8;
       }
      } else {
       decoded = 0x1e;
       code_len = 7;
      }
     } else {
      if ((code >> 6) & 0x1) {
       decoded = 0x15;
       code_len = 7;
      } else {
       decoded = 0x18;
       code_len = 7;
      }
     }
    }
   }
  } else {
   if ((code >> 3) & 0x1) {
    if ((code >> 4) & 0x1) {
     if ((code >> 5) & 0x1) {
      decoded = 0x14;
      code_len = 6;
     } else {
      decoded = 0xb;
      code_len = 6;
     }
    } else {
     decoded = 0x12;
     code_len = 5;
    }
   } else {
    if ((code >> 4) & 0x1) {
     decoded = 0x2;
     code_len = 5;
    } else {
     if ((code >> 5) & 0x1) {
      if ((code >> 6) & 0x1) {
       decoded = 0xd;
       code_len = 7;
      } else {
       decoded = 0x17;
       code_len = 7;
      }
     } else {
      decoded = 0xa;
      code_len = 6;
     }
    }
   }
  }
 } else {
  if ((code >> 2) & 0x1) {
   if ((code >> 3) & 0x1) {
    if ((code >> 4) & 0x1) {
     if ((code >> 5) & 0x1) {
      decoded = 0x6;
      code_len = 6;
     } else {
      if ((code >> 6) & 0x1) {
       decoded = 0x1b;
       code_len = 7;
      } else {
       decoded = 0x1d;
       code_len = 7;
      }
     }
    } else {
     if ((code >> 5) & 0x1) {
      decoded = 0xc;
      code_len = 6;
     } else {
      decoded = 0x16;
      code_len = 6;
     }
    }
   } else {
    if ((code >> 4) & 0x1) {
     decoded = 0x8;
     code_len = 5;
    } else {
     if ((code >> 5) & 0x1) {
      decoded = 0x9;
      code_len = 6;
     } else {
      decoded = 0x13;
      code_len = 6;
     }
    }
   }
  } else {
   if ((code >> 3) & 0x1) {
    decoded = 0x11;
    code_len = 4;
   } else {
    if ((code >> 4) & 0x1) {
     decoded = 0x3;
     code_len = 5;
    } else {
     decoded = 0x4;
     code_len = 5;
    }
   }
  }
 }
}
