// DO NOT EDIT - file generated by game/gen_huffman.py
if (code[0]) begin
 decoded = 32'hff334c4c;
 code_len = 8'd1;
end else begin
 if (code[1]) begin
  if (code[2]) begin
   decoded = 32'hffeaeaea;
   code_len = 8'd3;
  end else begin
   if (code[3]) begin
    if (code[4]) begin
     decoded = 32'hff1e1e1e;
     code_len = 8'd5;
    end else begin
     if (code[5]) begin
      decoded = 32'hff3b3b3b;
      code_len = 8'd6;
     end else begin
      if (code[6]) begin
       decoded = 32'hffeaea00;
       code_len = 8'd7;
      end else begin
       decoded = 32'hff3b3b00;
       code_len = 8'd7;
      end
     end
    end
   end else begin
    if (code[4]) begin
     decoded = 32'hff494949;
     code_len = 8'd5;
    end else begin
     if (code[5]) begin
      if (code[6]) begin
       decoded = 32'hff3b0000;
       code_len = 8'd7;
      end else begin
       if (code[7]) begin
        if (code[8]) begin
         decoded = 32'hff930000;
         code_len = 8'd9;
        end else begin
         decoded = 32'hff939393;
         code_len = 8'd9;
        end
       end else begin
        decoded = 32'hff939300;
        code_len = 8'd8;
       end
      end
     end else begin
      decoded = 32'hffea0000;
      code_len = 8'd6;
     end
    end
   end
  end
 end else begin
  decoded = 32'hff757575;
  code_len = 8'd2;
 end
end
