// DO NOT EDIT - file generated by game/gen_huffman.py
if (code[0]) begin
 decoded = 32'h20;
 code_len = 8'd1;
end else begin
 if (code[1]) begin
  if (code[2]) begin
   if (code[3]) begin
    if (code[4]) begin
     if (code[5]) begin
      decoded = 32'h14;
      code_len = 8'd6;
     end else begin
      if (code[6]) begin
       decoded = 32'h18;
       code_len = 8'd7;
      end else begin
       if (code[7]) begin
        decoded = 32'h17;
        code_len = 8'd8;
       end else begin
        decoded = 32'h19;
        code_len = 8'd8;
       end
      end
     end
    end else begin
     if (code[5]) begin
      if (code[6]) begin
       decoded = 32'ha;
       code_len = 8'd7;
      end else begin
       decoded = 32'h7;
       code_len = 8'd7;
      end
     end else begin
      decoded = 32'h1c;
      code_len = 8'd6;
     end
    end
   end else begin
    if (code[4]) begin
     if (code[5]) begin
      decoded = 32'h1;
      code_len = 8'd6;
     end else begin
      if (code[6]) begin
       decoded = 32'h1a;
       code_len = 8'd7;
      end else begin
       decoded = 32'h13;
       code_len = 8'd7;
      end
     end
    end else begin
     if (code[5]) begin
      decoded = 32'h8;
      code_len = 8'd6;
     end else begin
      if (code[6]) begin
       decoded = 32'hd;
       code_len = 8'd7;
      end else begin
       if (code[7]) begin
        decoded = 32'h1e;
        code_len = 8'd8;
       end else begin
        decoded = 32'h1f;
        code_len = 8'd8;
       end
      end
     end
    end
   end
  end else begin
   if (code[3]) begin
    if (code[4]) begin
     if (code[5]) begin
      if (code[6]) begin
       decoded = 32'h16;
       code_len = 8'd7;
      end else begin
       decoded = 32'h9;
       code_len = 8'd7;
      end
     end else begin
      decoded = 32'h6;
      code_len = 8'd6;
     end
    end else begin
     decoded = 32'h12;
     code_len = 8'd5;
    end
   end else begin
    if (code[4]) begin
     decoded = 32'h2;
     code_len = 8'd5;
    end else begin
     decoded = 32'h5;
     code_len = 8'd5;
    end
   end
  end
 end else begin
  if (code[2]) begin
   if (code[3]) begin
    if (code[4]) begin
     if (code[5]) begin
      decoded = 32'h3;
      code_len = 8'd6;
     end else begin
      decoded = 32'h15;
      code_len = 8'd6;
     end
    end else begin
     if (code[5]) begin
      if (code[6]) begin
       decoded = 32'h1d;
       code_len = 8'd7;
      end else begin
       decoded = 32'h1b;
       code_len = 8'd7;
      end
     end else begin
      decoded = 32'hf;
      code_len = 8'd6;
     end
    end
   end else begin
    decoded = 32'h11;
    code_len = 8'd4;
   end
  end else begin
   if (code[3]) begin
    if (code[4]) begin
     decoded = 32'he;
     code_len = 8'd5;
    end else begin
     if (code[5]) begin
      decoded = 32'hb;
      code_len = 8'd6;
     end else begin
      decoded = 32'hc;
      code_len = 8'd6;
     end
    end
   end else begin
    if (code[4]) begin
     decoded = 32'h4;
     code_len = 8'd5;
    end else begin
     decoded = 32'h10;
     code_len = 8'd5;
    end
   end
  end
 end
end
